# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew.
# DO NOT EDIT.

class LatentGate < Formula
  desc "Local-first vision-language pipeline — compress images, text, and documents via Ollama"
  homepage "https://github.com/KathanModh259/latent-gate"
  url "https://files.pythonhosted.org/packages/source/l/latent-gate/latent-gate-1.0.0.tar.gz"
  sha256 "REPLACE_WITH_ACTUAL_SHA256"
  license "MIT"

  depends_on "python@3.10"
  depends_on "ollama" => :recommended

  def install
    venv = virtualenv_create(libexec, "python3.10")
    venv.pip_install buildpath
    bin.install_symlink Formula["python@3.10"].opt_bin/"python3" => "python3"
  end

  test do
    system "#{bin}/latent-gate", "--help"
    system "python3", "-c", "from latent_gate import LatentGatePipeline; print('OK')"
  end
end
